window.INVENTORY_DATA = [
  {
    "code": "HP001",
    "category": "Hoparlör / Monitör",
    "name": "Electro-Voice Monitör",
    "brand": "Electro-Voice",
    "model": "",
    "system": 2,
    "physical": 2,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "HP002",
    "category": "Hoparlör / Monitör",
    "name": "MCS Monitör",
    "brand": "MCS",
    "model": "",
    "system": 2,
    "physical": 2,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "HP003",
    "category": "Hoparlör / Monitör",
    "name": "LG Hoparlör",
    "brand": "LG",
    "model": "",
    "system": 3,
    "physical": 3,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "MK001",
    "category": "Mikrofon",
    "name": "AVL Mikrofon",
    "brand": "AVL",
    "model": "",
    "system": 11,
    "physical": 11,
    "cabinet": "D3",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "MX001",
    "category": "Mikser",
    "name": "Studiomaster Mikser",
    "brand": "Studiomaster",
    "model": "",
    "system": 4,
    "physical": 4,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "MX002",
    "category": "Mikser",
    "name": "Yamaha MG20XU Mikser",
    "brand": "Yamaha",
    "model": "MG20XU",
    "system": 1,
    "physical": 1,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KB001",
    "category": "Kablo",
    "name": "XLR Uzatma",
    "brand": "",
    "model": "",
    "system": 2,
    "physical": 2,
    "cabinet": "D3",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "MK002",
    "category": "Mikrofon",
    "name": "Mikrofon Ayağı",
    "brand": "",
    "model": "",
    "system": 7,
    "physical": 7,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "HP004",
    "category": "Hoparlör / Monitör",
    "name": "Hoparlör Ayağı",
    "brand": "",
    "model": "",
    "system": 21,
    "physical": 21,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "MK003",
    "category": "Mikrofon",
    "name": "Stand Mikrofon Ayağı",
    "brand": "",
    "model": "",
    "system": 20,
    "physical": 20,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "KN001",
    "category": "Konnektör / Uç",
    "name": "XLR Jak Uç (Dişi)",
    "brand": "",
    "model": "",
    "system": 19,
    "physical": 19,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KN002",
    "category": "Konnektör / Uç",
    "name": "XLR Jak Uç (Erkek)",
    "brand": "",
    "model": "",
    "system": 14,
    "physical": 14,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KN003",
    "category": "Konnektör / Uç",
    "name": "Mono Jak 6.3 mm",
    "brand": "",
    "model": "",
    "system": 10,
    "physical": 10,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KN004",
    "category": "Konnektör / Uç",
    "name": "Stereo Uç",
    "brand": "",
    "model": "",
    "system": 17,
    "physical": 17,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KB002",
    "category": "Kablo",
    "name": "Kısa XLR Kablo",
    "brand": "",
    "model": "",
    "system": 14,
    "physical": 14,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KB003",
    "category": "Kablo",
    "name": "Jak-XLR Kablo",
    "brand": "",
    "model": "",
    "system": 14,
    "physical": 14,
    "cabinet": "D3",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KN005",
    "category": "Konnektör / Uç",
    "name": "Jak Uç",
    "brand": "",
    "model": "",
    "system": 4,
    "physical": 4,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "MK004",
    "category": "Mikrofon",
    "name": "Shure SV200 Vokal Mikrofon",
    "brand": "Shure",
    "model": "SV200",
    "system": 14,
    "physical": 13,
    "cabinet": "D1",
    "status": "Eksik",
    "usage": "Kilitli"
  },
  {
    "code": "MK005",
    "category": "Mikrofon",
    "name": "Shure BLX Mikrofon",
    "brand": "Shure",
    "model": "BLX",
    "system": 7,
    "physical": 7,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "MK006",
    "category": "Mikrofon",
    "name": "HEPA MERZ HX-101 Headset Mikrofon",
    "brand": "HEPA MERZ",
    "model": "HX-101",
    "system": 9,
    "physical": 9,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "KB004",
    "category": "Kablo",
    "name": "Spekon Kablosuz Mikrofon Seti",
    "brand": "Spekon",
    "model": "",
    "system": 9,
    "physical": 9,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "MK007",
    "category": "Mikrofon",
    "name": "CR-702 Masa Mikrofonu",
    "brand": "CR-702",
    "model": "CR-702",
    "system": 2,
    "physical": 2,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "MK008",
    "category": "Mikrofon",
    "name": "Shure Kürsü Mikrofonu",
    "brand": "Shure",
    "model": "",
    "system": 3,
    "physical": 3,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "MK009",
    "category": "Mikrofon",
    "name": "Shure Kürsü Mikrofon Tablası",
    "brand": "Shure",
    "model": "",
    "system": 5,
    "physical": 5,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "MK010",
    "category": "Mikrofon",
    "name": "Shure PGA31 Headset Mikrofon",
    "brand": "Shure",
    "model": "PGA31",
    "system": 6,
    "physical": 6,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "MK011",
    "category": "Mikrofon",
    "name": "Denox Mikrofon",
    "brand": "Denox",
    "model": "",
    "system": 4,
    "physical": 4,
    "cabinet": "D3",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "MK012",
    "category": "Mikrofon",
    "name": "Shure Yaka Mikrofon",
    "brand": "Shure",
    "model": "",
    "system": 1,
    "physical": 1,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "MK013",
    "category": "Mikrofon",
    "name": "Koro Mikrofonu",
    "brand": "",
    "model": "",
    "system": 3,
    "physical": 3,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "MK014",
    "category": "Mikrofon",
    "name": "Shure SM57",
    "brand": "Shure",
    "model": "SM57",
    "system": 5,
    "physical": 5,
    "cabinet": "D1",
    "status": "Depoda",
    "usage": "Kilitli"
  },
  {
    "code": "HP005",
    "category": "Hoparlör / Monitör",
    "name": "Electro-Voice Bass",
    "brand": "Electro-Voice",
    "model": "",
    "system": 2,
    "physical": 2,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "HP006",
    "category": "Hoparlör / Monitör",
    "name": "Electro-Voice Üst",
    "brand": "Electro-Voice",
    "model": "",
    "system": 2,
    "physical": 2,
    "cabinet": "D4",
    "status": "Depoda",
    "usage": "Pasif / Kontrol"
  },
  {
    "code": "KB005",
    "category": "Kablo",
    "name": "Jak Kablo",
    "brand": "",
    "model": "",
    "system": 3,
    "physical": 3,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  },
  {
    "code": "KB006",
    "category": "Kablo",
    "name": "XLR Kablo",
    "brand": "",
    "model": "",
    "system": 17,
    "physical": 17,
    "cabinet": "D2",
    "status": "Depoda",
    "usage": "Aktif"
  }
];
